(function(w,d){'use strict';
var auth=w.TaeDoSAAuth,form=d.getElementById('developmentApplyForm'),msg=d.getElementById('formMessage'),loginNotice=d.getElementById('loginNotice');if(!form)return;
init();
async function init(){bind();await fillSession();}
function bind(){d.querySelectorAll('input[name="siteType"]').forEach(function(el){el.addEventListener('change',function(){conditional(this.value);});});var btn=d.getElementById('siteAddressSearch');if(btn)btn.addEventListener('click',searchAddress);form.addEventListener('submit',submit);}
function conditional(v){d.getElementById('landUseField').hidden=v!=='land';d.getElementById('buildingUseField').hidden=v!=='roof';d.getElementById('drawingField').hidden=v!=='roof';}
async function fillSession(){if(!auth)return;try{var out=await auth.getSession({force:true}),member=out&&out.response&&out.response.ok&&out.result&&out.result.authenticated?out.result.member:null;if(!member){if(loginNotice)loginNotice.hidden=false;return;}set('applicantName',member.name||member.companyName||member.company_name||'');set('applicantPhone',phone(member.phone||''));set('applicantEmail',member.email||'');var type=String(member.memberType||member.member_type||'').toLowerCase();radio('applicantType',type.includes('business')?'business':'personal');}catch(e){if(loginNotice)loginNotice.hidden=false;}}
function searchAddress(){if(!w.daum||!w.daum.Postcode){show('주소검색 서비스를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.',true);return;}new w.daum.Postcode({oncomplete:function(data){d.getElementById('siteAddress').value=data.roadAddress||data.jibunAddress||'';}}).open({popupTitle:'태도사 주소검색'});}
async function submit(e){e.preventDefault();clear();if(!form.reportValidity())return;if(!auth||!auth.createDevelopmentRequest){show('신청 서비스를 불러오지 못했습니다. 페이지를 새로고침해 주세요.',true);return;}var button=form.querySelector('button[type="submit"]');button.disabled=true;button.textContent='신청 접수 중...';try{var payload={formVersion:'DEVELOPMENT_PERMIT_APPLY_V1',applicantType:radioValue('applicantType'),applicantName:value('applicantName'),applicantPhone:value('applicantPhone'),applicantEmail:value('applicantEmail'),precheckStatus:radioValue('precheckStatus'),businessLicenseStatus:radioValue('businessLicenseStatus'),licenseNumber:value('licenseNumber'),licenseDate:value('licenseDate'),lineCapacity:radioValue('lineCapacity'),siteRights:radioValue('siteRights'),siteType:radioValue('siteType'),siteAddress:value('siteAddress'),capacity:value('capacity'),landUse:value('landUse'),buildingUse:value('buildingUse'),drawingStatus:radioValue('drawingStatus'),siteNotes:value('siteNotes'),preferredVisit:value('preferredVisit'),siteContact:value('siteContact'),visitNotes:value('visitNotes'),additionalRequest:value('additionalRequest'),privacyConsent:checked('privacyConsent'),applicationConfirmed:checked('applicationConfirmation')};var out=await auth.createDevelopmentRequest(payload),r=out.result||{};if(!out.response.ok||!r.success)throw new Error(r.message||'신청을 접수하지 못했습니다.');show((r.message||'신청이 완료되었습니다.')+' 신청번호: '+(r.request&&r.request.requestNo||'-'),false);form.querySelectorAll('input,textarea,button').forEach(function(el){el.disabled=true;});}catch(err){show(err&&err.message?err.message:'신청 접수 중 오류가 발생했습니다.',true);button.disabled=false;button.textContent='개발행위허가 신청하기';}}
function control(name){return form.elements.namedItem(name);}function value(name){var el=control(name);return el?String(el.value||'').normalize('NFKC').trim():'';}function checked(name){var el=control(name);return !!(el&&el.checked);}function radioValue(name){var el=form.querySelector('input[name="'+name+'"]:checked');return el?el.value:'';}function radio(name,v){var el=form.querySelector('input[name="'+name+'"][value="'+v+'"]');if(el)el.checked=true;}function set(name,v){var el=control(name);if(el)el.value=v;}function phone(v){var x=String(v||'').replace(/\D/g,'').slice(0,11);if(x.length<4)return x;if(x.length<8)return x.slice(0,3)+'-'+x.slice(3);return x.slice(0,3)+'-'+x.slice(3,x.length===10?6:7)+'-'+x.slice(x.length===10?6:7);}function show(t,error){msg.hidden=false;msg.textContent=t;msg.className='form-message '+(error?'error':'success');msg.scrollIntoView({behavior:'smooth',block:'center'});}function clear(){msg.hidden=true;msg.textContent='';msg.className='form-message';}
})(window,document);
